#!/usr/bin/env node
/**
 * build-tokens.js
 *
 * Reads tokens/tokens.json and writes:
 *   assets/css/tokens.css  ->  :root { --token-name: value; ... }
 *   assets/js/tokens.js    ->  window.OW_TOKENS = { values, list }
 *
 * Usage:
 *   node scripts/build-tokens.js          write the generated files
 *   node scripts/build-tokens.js --check  exit 1 if the generated files are out of date
 *
 * No dependencies — runs on any Node >= 16.
 *
 * Token format (a small subset of the W3C Design Tokens draft):
 *   - A token is any object with a "$value".
 *   - Top-level keys are groups. The CSS variable name is  --<prefix>-<path>,
 *     where <prefix> defaults to the group name and can be overridden with
 *     "$cssPrefix" (use "" for no prefix, as the color group does).
 *   - "$type" may be set on a token or inherited from its group.
 *   - "$rgb": true on a hex color also emits --<name>-rgb: r, g, b  so CSS can
 *     do  rgba(var(--accent-selected-rgb), 0.4).
 *   - A value of the form "{group.key}" is an alias. CSS gets var(--target);
 *     JS gets the resolved literal value.
 *   - Keys starting with "$" are metadata and never become tokens.
 */
"use strict";

const fs = require("fs");
const path = require("path");

const ROOT = path.resolve(__dirname, "..");
const SRC = path.join(ROOT, "tokens", "tokens.json");
const OUT_CSS = path.join(ROOT, "assets", "css", "tokens.css");
const OUT_JS = path.join(ROOT, "assets", "js", "tokens.js");
const BANNER = "AUTO-GENERATED by scripts/build-tokens.js from tokens/tokens.json — do not edit by hand.";

const ALIAS_RE = /^\{([^}]+)\}$/;
const NAME_RE = /^[a-z0-9]+(-[a-z0-9]+)*$/;

function fail(msg) {
  console.error("✖ " + msg);
  process.exit(1);
}

/* ---------- 1. Flatten the JSON tree into a list of tokens ---------- */
function flatten(json) {
  const tokens = [];
  for (const [groupKey, group] of Object.entries(json)) {
    if (groupKey.startsWith("$")) continue;
    if (!group || typeof group !== "object") fail(`Top-level "${groupKey}" must be a group object.`);
    const prefix = group.$cssPrefix !== undefined ? group.$cssPrefix : groupKey;
    walk(group, [], groupKey, prefix, group.$type, tokens);
  }
  return tokens;
}

function walk(node, trail, groupKey, prefix, inheritedType, out) {
  for (const [key, child] of Object.entries(node)) {
    if (key.startsWith("$")) continue;
    const dotted = [groupKey, ...trail, key].join(".");
    if (child && typeof child === "object" && "$value" in child) {
      const name = [prefix, ...trail, key].filter(Boolean).join("-");
      if (!NAME_RE.test(name)) fail(`Token "${dotted}" produces invalid CSS name "--${name}" (use lowercase letters, digits, hyphens).`);
      out.push({
        name,
        path: dotted,
        group: groupKey,
        type: child.$type || inheritedType || "other",
        raw: String(child.$value),
        description: child.$description || "",
        rgb: child.$rgb === true
      });
    } else if (child && typeof child === "object") {
      walk(child, [...trail, key], groupKey, prefix, child.$type || inheritedType, out);
    } else {
      fail(`"${dotted}" must be a token object with a "$value" or a nested group.`);
    }
  }
}

/* ---------- 2. Resolve aliases and validate ---------- */
function resolve(tokens) {
  const byPath = new Map(tokens.map((t) => [t.path, t]));
  const seen = new Map();
  for (const t of tokens) {
    if (seen.has(t.name)) fail(`Duplicate CSS variable --${t.name} (from "${seen.get(t.name)}" and "${t.path}").`);
    seen.set(t.name, t.path);
  }

  function resolveValue(t, stack) {
    const m = ALIAS_RE.exec(t.raw);
    if (!m) return t.raw;
    const target = byPath.get(m[1]);
    if (!target) fail(`Token "${t.path}" references unknown token "{${m[1]}}".`);
    if (stack.includes(target.path)) fail(`Alias cycle: ${[...stack, target.path].join(" -> ")}`);
    return resolveValue(target, [...stack, target.path]);
  }

  for (const t of tokens) {
    const m = ALIAS_RE.exec(t.raw);
    t.alias = m ? m[1] : null;
    t.value = resolveValue(t, [t.path]);
    t.css = m ? `var(--${tokens.find((x) => x.path === m[1]).name})` : t.raw;
    if (t.rgb) {
      t.rgbValue = hexToRgb(t.value);
      if (!t.rgbValue) fail(`Token "${t.path}" has "$rgb": true but "${t.value}" is not a hex color.`);
    }
  }
  return tokens;
}

function hexToRgb(hex) {
  let h = String(hex).trim().replace(/^#/, "");
  if (/^[0-9a-f]{3}$/i.test(h)) h = h.split("").map((c) => c + c).join("");
  if (!/^[0-9a-f]{6}$/i.test(h)) return null;
  const n = parseInt(h, 16);
  return `${(n >> 16) & 255}, ${(n >> 8) & 255}, ${n & 255}`;
}

/* ---------- 3. Render outputs ---------- */
function renderCss(tokens) {
  const lines = [`/* ${BANNER} */`, "", ":root {"];
  let group = null;
  for (const t of tokens) {
    if (t.group !== group) {
      if (group !== null) lines.push("");
      lines.push(`  /* ${t.group} */`);
      group = t.group;
    }
    const comment = t.description ? ` /* ${t.description.replace(/\*\//g, "* /")} */` : "";
    lines.push(`  --${t.name}: ${t.css};${comment}`);
    if (t.rgb) lines.push(`  --${t.name}-rgb: ${t.rgbValue};`);
  }
  lines.push("}", "");
  return lines.join("\n");
}

function renderJs(tokens) {
  const values = {};
  for (const t of tokens) {
    values[t.name] = t.value;
    if (t.rgb) values[t.name + "-rgb"] = t.rgbValue;
  }
  const list = tokens.map((t) => ({
    name: t.name,
    group: t.group,
    type: t.type,
    value: t.value,
    alias: t.alias,
    description: t.description
  }));
  return (
    `/* ${BANNER} */\n` +
    "window.OW_TOKENS = Object.freeze(" +
    JSON.stringify({ values, list }, null, 2) +
    ");\n"
  );
}

/* ---------- 4. Main ---------- */
function main() {
  const check = process.argv.includes("--check");
  let json;
  try {
    json = JSON.parse(fs.readFileSync(SRC, "utf8"));
  } catch (err) {
    fail(`Could not read ${path.relative(ROOT, SRC)}: ${err.message}`);
  }

  const tokens = resolve(flatten(json));
  const outputs = [
    [OUT_CSS, renderCss(tokens)],
    [OUT_JS, renderJs(tokens)]
  ];

  if (check) {
    const stale = outputs.filter(([file, content]) => !fs.existsSync(file) || fs.readFileSync(file, "utf8") !== content);
    if (stale.length) {
      stale.forEach(([file]) => console.error("✖ out of date: " + path.relative(ROOT, file)));
      fail("Generated token files are stale. Run `npm run build:tokens` and commit the result.");
    }
    console.log(`✔ ${tokens.length} tokens, generated files are up to date.`);
    return;
  }

  for (const [file, content] of outputs) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
    console.log("✔ wrote " + path.relative(ROOT, file));
  }
  console.log(`  ${tokens.length} tokens from ${path.relative(ROOT, SRC)}`);
}

main();
